name: Docker build

on:
  push:
    branches:
      - main
      - github-action-for-nro
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build the project using Docker
        run: |
          docker build -t romlauncher-builder .
          docker run --name extract-container romlauncher-builder
          docker cp extract-container:/usr/src/project/romlauncher.nro romlauncher.nro
          docker rm extract-container

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: romlauncher.nro
          path: romlauncher.nro
